package loecraftpack.enums;

public enum LivingEventId {
	LIVING_FALL,
	LIVING_ATTACK,
	LIVING_HURT,
	LIVING_DEATH,
	LIVING_DEATH_PRE,
	ENTITY_ITEM_PICKUP,
	PLAYER_SLEEP_IN_BED,
	ENTITY_INTERACT,
	ATTACK_ENTITY,
	USE_HOE,
	BONEMEAL,
	FILL_BUCKET,
	PLAYER_DESTROY_ITEM,
	PLAYER_FLYABLE_FALL,
	PLAYER_DROPS,
	ARROW_LOOSE,
	ARROW_NOCK,
	
	ENDER_TELEPORT,
	LIVING_DROPS,
	LIVING_SET_ATTACK_TARGET,
	LIVING_SPAWN,
}
